# Generated by Django 4.2.15 on 2024-09-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company", name="domain", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="companymanager",
            name="app_password",
            field=models.CharField(max_length=255),
        ),
    ]
