# Generated by Django 4.2.15 on 2024-11-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sender_app", "0002_alter_company_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymanager",
            name="send_mails",
            field=models.BooleanField(default=True),
        ),
    ]
